steps:
  # Build the Docker Image
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/amazing-employees/amazing-employees-backend-service:latest', '.']


  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/amazing-employees/amazing-employees-backend-service:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'amazing-employees-backend-service',
      '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/amazing-employees/amazing-employees-backend-service:latest',
      '--region', '$LOCATION',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--service-account', 'employees-backend-sa@$PROJECT_ID.iam.gserviceaccount.com',
      '--max-instances', '2',
    ]

images: ['$LOCATION-docker.pkg.dev/$PROJECT_ID/amazing-employees/amazing-employees-backend-service:latest']
options:
  logging: CLOUD_LOGGING_ONLY
